//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelData
    {
        public int HotelID { get; set; }
        public string HotelName { get; set; }
        public Nullable<float> Ratings { get; set; }
        public string Category { get; set; }
        public Nullable<bool> FreeWifi { get; set; }
        public float PriceRangeUpper { get; set; }
        public float PriceRangeLower { get; set; }
        public int RoomAvailable { get; set; }
        public Nullable<bool> SwimmingPool { get; set; }
        public Nullable<bool> CarPark { get; set; }
        public Nullable<bool> FreeBreakfast { get; set; }
        public Nullable<bool> PrivateParking { get; set; }
        public Nullable<bool> PlayLand { get; set; }
    }
}
