//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HotelData
    {
        [Required(ErrorMessage = "Please enter Hotel name")]
        public int HotelID { get; set; }
        public string HotelName { get; set; }
        public Nullable<float> Ratings { get; set; }
        public string Category { get; set; }
        public bool FreeWifi { get; set; }
        public float PriceRangeUpper { get; set; }
        public float PriceRangeLower { get; set; }
        public int RoomAvailable { get; set; }
        public bool SwimmingPool { get; set; }
        public bool CarPark { get; set; }
        public bool FreeBreakfast { get; set; }
        public bool PrivateParking { get; set; }
        public bool PlayLand { get; set; }
        public string About { get; set; }
    }
}
